name: Example Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 22f2001630@ds.study.iitm.ac.in
        run: echo "Hello, world!"
